# Generated by Django 3.0.5 on 2022-05-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
